"""Validated contracts shared by deterministic and future AI components."""

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field, model_validator


class FactStatus(str, Enum):
    """Explicit tri-state for facts that may not yet be known."""

    TRUE = "true"
    FALSE = "false"
    UNKNOWN = "unknown"


class EventType(str, Enum):
    """Structured event types grounded in the Policy covered-events list."""

    ACCIDENTAL_COLLISION = "accidental_collision"
    THEFT = "theft"
    FIRE = "fire"
    FLOOD = "flood"
    THIRD_PARTY_PROPERTY_DAMAGE = "third_party_property_damage"
    OTHER = "other"
    UNKNOWN = "unknown"


class CoverageAssessment(str, Enum):
    LIKELY_COVERED = "Likely covered"
    POSSIBLY_COVERED = "Possibly covered"
    NOT_COVERED = "Not covered"
    CANNOT_DETERMINE = "Cannot determine"


class Routing(str, Enum):
    STANDARD_PROCESSING = "Standard processing"
    MANUAL_REVIEW = "Manual review"
    FRAUD_REVIEW = "Fraud review"
    REJECTION_REVIEW = "Rejection review"


class ConfidenceLevel(str, Enum):
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"


class ClaimInput(BaseModel):
    """Assignment claim input fields; free text is data, not rule input."""

    claim_id: str
    customer: str | None = None
    vehicle: str | None = None
    incident_date: date | None = None
    claim_submitted_date: date | None = None
    claim_description: str
    documents_submitted: list[str] = Field(default_factory=list)
    customer_claim_history: str | None = None


class ClaimFacts(BaseModel):
    """Validated semantic facts consumed by deterministic engines.

    A future LLM may propose these values, but it is not a dependency of this
    model or of the deterministic processing flow.
    """

    event_type: EventType = EventType.UNKNOWN
    alcohol_or_drug_involvement: FactStatus = FactStatus.UNKNOWN
    illegal_racing: FactStatus = FactStatus.UNKNOWN
    intentional_damage: FactStatus = FactStatus.UNKNOWN
    outside_permitted_geographic_coverage: FactStatus = FactStatus.UNKNOWN
    late_submission_valid_reason: FactStatus = FactStatus.UNKNOWN
    suspicious_pattern: FactStatus = FactStatus.UNKNOWN
    inconsistent_story: FactStatus = FactStatus.UNKNOWN
    repeated_claims: FactStatus = FactStatus.UNKNOWN
    severe_damage: FactStatus = FactStatus.UNKNOWN
    weak_evidence: FactStatus = FactStatus.UNKNOWN


class LLMExtractionPayload(BaseModel):
    """Flat, strict schema generated by the LLM before canonical conversion.

    The canonical ClaimFacts contract remains the only semantic input to P0.
    This flat boundary avoids asking a small local model to generate a nested
    facts-and-evidence structure in one response.
    """

    event_type: EventType = Field(
        description="Explicit event type; use unknown only when the event is not established."
    )
    alcohol_or_drug_involvement: FactStatus = Field(
        description="true if explicitly involved, false if explicitly ruled out, otherwise unknown."
    )
    illegal_racing: FactStatus = Field(
        description="true if illegal racing is explicit, false if explicitly ruled out, otherwise unknown."
    )
    intentional_damage: FactStatus = Field(
        description="true if intentional damage is explicit, false if explicitly ruled out, otherwise unknown."
    )
    outside_permitted_geographic_coverage: FactStatus = Field(
        description="true or false only from explicit geographic evidence; otherwise unknown."
    )
    late_submission_valid_reason: FactStatus = Field(
        description="true when a valid reason is stated, false when absence of a reason is explicit, otherwise unknown."
    )
    suspicious_pattern: FactStatus = Field(
        description="true only when the supplied claim data explicitly supports a suspicious pattern."
    )
    inconsistent_story: FactStatus = Field(
        description="true only when supplied statements explicitly conflict; otherwise unknown unless consistency is explicit."
    )
    repeated_claims: FactStatus = Field(
        description="true for explicit repeated/multiple claims, false for explicit no prior claims, otherwise unknown."
    )
    severe_damage: FactStatus = Field(
        description="true when severe damage is explicit, false when explicitly described as not severe, otherwise unknown."
    )
    weak_evidence: FactStatus = Field(
        description="true when evidence is explicitly weak or unclear, false when explicitly adequate, otherwise unknown."
    )


class EventExclusionExtraction(BaseModel):
    """Focused LLM payload for event and explicit exclusion semantics."""

    event_type: EventType
    alcohol_or_drug_involvement: FactStatus
    illegal_racing: FactStatus
    intentional_damage: FactStatus
    outside_permitted_geographic_coverage: FactStatus


class HistoryRiskExtraction(BaseModel):
    """Focused LLM payload for claim-history and semantic risk signals."""

    suspicious_pattern: FactStatus
    inconsistent_story: FactStatus
    repeated_claims: FactStatus
    severe_damage: FactStatus
    weak_evidence: FactStatus


class LateReasonExtraction(BaseModel):
    """Focused LLM payload for the stated presence or absence of a late reason."""

    late_submission_valid_reason: FactStatus


class FocusedGroupResult(BaseModel):
    """Observable execution status for one validated focused extraction call."""

    group: str
    success: bool
    retry_count: int = Field(default=0, ge=0, le=1)
    latency_seconds: float = Field(ge=0)
    error: str | None = None
    error_code: str | None = None


class FocusedSemanticExtractionResult(BaseModel):
    """Composed canonical facts plus per-group validation/fallback status."""

    success: bool
    facts: ClaimFacts
    groups: list[FocusedGroupResult]
    failed_groups: list[str] = Field(default_factory=list)
    provider: str | None = None
    model: str | None = None


class SemanticFactProposal(BaseModel):
    """Untrusted semantic suggestions that must never enter P0 directly."""

    facts: ClaimFacts = Field(default_factory=ClaimFacts)
    source: Literal["llm", "safe_fallback"]
    confirmed: Literal[False] = False
    extraction_success: bool
    provider: str | None = None
    model: str | None = None
    failed_groups: list[str] = Field(default_factory=list)
    warning: str = "LLM suggestions are advisory and require human confirmation."


class HumanReviewPayload(BaseModel):
    """Stage-one result presented for mandatory officer review/correction."""

    claim: ClaimInput
    proposal: SemanticFactProposal
    confirmation_required: Literal[True] = True


class ConfirmedClaimFacts(BaseModel):
    """Only this explicit human-confirmation contract may cross into P0."""

    claim_id: str
    facts: ClaimFacts
    confirmed_by_human: Literal[True]
    officer_note: str | None = None


class EvidenceSource(str, Enum):
    CLAIM_DESCRIPTION = "claim_description"
    CUSTOMER_CLAIM_HISTORY = "customer_claim_history"
    STRUCTURED_CLAIM_INPUT = "structured_claim_input"


class SemanticFactName(str, Enum):
    EVENT_TYPE = "event_type"
    ALCOHOL_OR_DRUG_INVOLVEMENT = "alcohol_or_drug_involvement"
    ILLEGAL_RACING = "illegal_racing"
    INTENTIONAL_DAMAGE = "intentional_damage"
    OUTSIDE_PERMITTED_GEOGRAPHIC_COVERAGE = "outside_permitted_geographic_coverage"
    LATE_SUBMISSION_VALID_REASON = "late_submission_valid_reason"
    SUSPICIOUS_PATTERN = "suspicious_pattern"
    INCONSISTENT_STORY = "inconsistent_story"
    REPEATED_CLAIMS = "repeated_claims"
    SEVERE_DAMAGE = "severe_damage"
    WEAK_EVIDENCE = "weak_evidence"


class FactEvidence(BaseModel):
    """Observable input evidence for a proposed semantic fact, not reasoning."""

    fact_name: SemanticFactName
    source: EvidenceSource
    text: str = Field(min_length=1, max_length=500)


class SemanticExtractionPayload(BaseModel):
    """Strict structured payload expected from the semantic LLM."""

    facts: ClaimFacts
    evidence: list[FactEvidence] = Field(default_factory=list)

    @model_validator(mode="before")
    @classmethod
    def require_all_fact_fields(cls, value: Any) -> Any:
        if not isinstance(value, dict):
            return value
        facts = value.get("facts")
        if not isinstance(facts, dict):
            return value
        expected = set(ClaimFacts.model_fields)
        missing = sorted(expected - set(facts))
        if missing:
            raise ValueError(
                "Structured extraction is missing fact fields: " + ", ".join(missing)
            )
        return value


class SemanticExtractionResult(BaseModel):
    """Safe application result; failed extraction always carries unknown facts."""

    success: bool
    facts: ClaimFacts = Field(default_factory=ClaimFacts)
    evidence: list[FactEvidence] = Field(default_factory=list)
    error: str | None = None
    error_code: str | None = None
    provider: str | None = None
    model: str | None = None
    retry_count: int = Field(default=0, ge=0, le=1)


class DocumentRequirement(BaseModel):
    identifier: str
    policy_wording: str


class DocumentCheckResult(BaseModel):
    required_documents: list[DocumentRequirement]
    submitted_document_ids: list[str]
    missing_document_ids: list[str]
    missing_information: list[str]


class CoverageEvaluation(BaseModel):
    assessment: CoverageAssessment
    is_covered_event: FactStatus
    submission_delay_days: int | None = None
    triggered_exclusions: list[str] = Field(default_factory=list)
    unresolved_information: list[str] = Field(default_factory=list)


class RiskEvaluation(BaseModel):
    risk_flags: list[str] = Field(default_factory=list)
    fraud_conclusion: bool = False


class DeterministicAnalysisResult(BaseModel):
    document_check: DocumentCheckResult
    coverage: CoverageEvaluation
    risk: RiskEvaluation
    recommended_routing: Routing
    missing_information: list[str] = Field(default_factory=list)
    reasoning_points: list[str] = Field(default_factory=list)


class TriageResult(BaseModel):
    """Final assignment contract, ready for later summary/explanation work."""

    claim_summary: str
    initial_coverage_assessment: CoverageAssessment
    missing_information: list[str]
    risk_flags: list[str]
    recommended_routing: Routing
    reasoning: str
    confidence_level: ConfidenceLevel


class ConfirmedTriageResult(BaseModel):
    """Presentation-ready backend result derived from confirmed facts and P0."""

    claim_id: str
    proposed_facts: ClaimFacts
    confirmed_facts: ClaimFacts
    initial_coverage_assessment: CoverageAssessment
    missing_documents: list[str]
    missing_information: list[str]
    risk_flags: list[str]
    recommended_routing: Routing
    deterministic_reasoning_points: list[str]
    claim_summary: str
    explanation: str
    human_confirmation_status: Literal["confirmed"] = "confirmed"
    recommendation_disclaimer: str = (
        "This is a triage recommendation, not a final claim decision. "
        "The Human Claim Officer remains the final decision maker."
    )
